# Generated by Django 4.2 on 2023-05-09 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='poll',
            name='quantity',
            field=models.FloatField(default=0),
        ),
    ]
