# Generated by Django 4.2 on 2023-05-10 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='percent_change_1h',
        ),
        migrations.AddField(
            model_name='currency',
            name='cmc_rank',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='currency',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='currency',
            name='market_cap',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='currency',
            name='percent_change_7d',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='image',
            field=models.ImageField(default='', max_length=254, upload_to='currency'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='percent_change_24h',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='volume_24h',
            field=models.FloatField(max_length=10, null=True),
        ),
    ]
